// Generated by CoffeeScript 1.4.0
(function() {

  chrome.contextMenus.onClicked.addListener(function(info, tab) {
    var _this = this;
    return chrome.tabs.create({
      "active": true,
      "url": chrome.extension.getURL('render.html')
    }, function(tab) {
      var port;
      port = chrome.extension.connect({
        name: 'renderHTMl'
      });
      return port.postMessage(['renderhtml', info.selectionText]);
    });
  });

  chrome.runtime.onInstalled.addListener(function() {
    console.log('fdafa');
    return chrome.contextMenus.create({
      "title": "Render Selection as HTML",
      "contexts": ["selection"],
      "id": "renderhtml"
    });
  });

}).call(this);
