// Generated by CoffeeScript 1.4.0
(function() {

  chrome.contextMenus.onClicked.addListener(function(info, tab) {
    var selection,
      _this = this;
    if (info.menuItemId === 'renderselection') {
      selection = info.selectionText;
      return chrome.tabs.create({
        "active": true,
        "url": chrome.extension.getURL('render.html')
      }, function(tab) {
        var port;
        port = chrome.extension.connect({
          name: 'renderHTMl'
        });
        return port.postMessage(['renderhtml', selection]);
      });
    } else if (info.menuItemId === 'renderclipboard') {
      return chrome.tabs.create({
        "active": true,
        "url": chrome.extension.getURL('render.html')
      }, function(tab) {
        var port;
        port = chrome.extension.connect({
          name: 'renderHTMl'
        });
        return port.postMessage(['renderclipboard']);
      });
    }
  });

  chrome.runtime.onInstalled.addListener(function() {
    chrome.contextMenus.create({
      "title": "Render Selection as HTML",
      "contexts": ["selection"],
      "id": "renderselection"
    });
    return chrome.contextMenus.create({
      "title": "Render Clipboard as HTML",
      "contexts": ["page"],
      "id": "renderclipboard"
    });
  });

}).call(this);
