// Generated by CoffeeScript 1.4.0
(function() {
  var activeListeners;

  activeListeners = {};

  chrome.extension.onConnect.addListener(function(port) {
    return port.onMessage.addListener(function(message) {
      var selection;
      if (message[0] === 'renderhtml') {
        selection = message[1];
        return document.body.innerHTML = selection;
      }
    });
  });

}).call(this);
